In [1]:
import cProfile
import pstats
from pstats import SortKey
import numpy as np
import os
os.getcwd()

'C:\\Users\\enrik\\Desktop\\Mabomba\\Studie\\MasterCS\\Thesis\\code\\plot_notebooks'

In [2]:
os.chdir("../")
os.getcwd()

'C:\\Users\\enrik\\Desktop\\Mabomba\\Studie\\MasterCS\\Thesis\\code'

In [3]:
from helpers.group_helpers import get_all_cycles

states = 4
cycles = get_all_cycles(states)
a = np.arange(states)
cycles

[[3, 0, 1, 2],
 [3, 0, 2, 1],
 [3, 1, 0, 2],
 [3, 1, 2, 0],
 [3, 2, 0, 1],
 [3, 2, 1, 0],
 [[1, 2], [0, 3]],
 [[1, 3], [0, 2]],
 [[2, 3], [0, 1]]]

In [4]:
def get_cycle(a,cur):
    b = []
    for i in a:
        curix = np.where(cur==i)
        wlast = curix[:-1]
        if len(wlast) == 0:
            curlen = len(cur)
            lastix = curix[0]
            newix = (lastix+1)%curlen
            newval = cur[newix]
        else:
            curlen = len(cur[wlast][0])
            lastix = curix[-1:][0]
            newix = (lastix+1)%curlen
            newval = cur[wlast][0][newix]    
        b.append(newval[0])
    return b

def compute_cycle(c1,c2,a):
    print(a)
    b = get_cycle(a,np.array(c1))
    c = get_cycle(b,np.array(c2))
    print(c)
    valid_comb = np.all((a==np.array(c)) == False)
    print(valid_comb)

In [6]:
for c1 in cycles:
    for c2 in cycles:
        print(c1,c2)
        compute_cycle(c1,c2,a)

[3, 0, 1, 2] [3, 0, 1, 2]
[0 1 2 3]
[2, 3, 0, 1]
True
[3, 0, 1, 2] [3, 0, 2, 1]
[0 1 2 3]
[3, 1, 0, 2]
False
[3, 0, 1, 2] [3, 1, 0, 2]
[0 1 2 3]
[0, 3, 1, 2]
False
[3, 0, 1, 2] [3, 1, 2, 0]
[0 1 2 3]
[2, 0, 1, 3]
False
[3, 0, 1, 2] [3, 2, 0, 1]
[0 1 2 3]
[3, 0, 2, 1]
False
[3, 0, 1, 2] [3, 2, 1, 0]
[0 1 2 3]
[0, 1, 2, 3]
False
[3, 0, 1, 2] [[1, 2], [0, 3]]
[0 1 2 3]
[2, 1, 0, 3]
False
[3, 0, 1, 2] [[1, 3], [0, 2]]
[0 1 2 3]
[3, 0, 1, 2]
True
[3, 0, 1, 2] [[2, 3], [0, 1]]
[0 1 2 3]
[0, 3, 2, 1]
False
[3, 0, 2, 1] [3, 0, 1, 2]
[0 1 2 3]
[3, 0, 2, 1]
False
[3, 0, 2, 1] [3, 0, 2, 1]
[0 1 2 3]
[1, 0, 3, 2]
True
[3, 0, 2, 1] [3, 1, 0, 2]
[0 1 2 3]
[3, 1, 0, 2]
False
[3, 0, 2, 1] [3, 1, 2, 0]
[0 1 2 3]
[0, 1, 2, 3]
False
[3, 0, 2, 1] [3, 2, 0, 1]
[0 1 2 3]
[0, 2, 3, 1]
False
[3, 0, 2, 1] [3, 2, 1, 0]
[0 1 2 3]
[1, 2, 0, 3]
False
[3, 0, 2, 1] [[1, 2], [0, 3]]
[0 1 2 3]
[1, 0, 2, 3]
False
[3, 0, 2, 1] [[1, 3], [0, 2]]
[0 1 2 3]
[0, 1, 3, 2]
False
[3, 0, 2, 1] [[2, 3], [0, 1]]
[0 1 2 3]
[3, 2, 0

In [15]:
# get_all_cycles(5)
cProfile.run('get_all_cycles(5)','test')
p = pstats.Stats('test')
p.strip_dirs().sort_stats('cumtime').print_stats(30)

Fri Mar  4 17:15:09 2022    test

         576791 function calls (572984 primitive calls) in 0.425 seconds

   Ordered by: cumulative time
   List reduced from 536 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.425    0.425 {built-in method builtins.exec}
        1    0.000    0.000    0.425    0.425 <string>:1(<module>)
        1    0.000    0.000    0.425    0.425 group_helpers.py:59(get_all_cycles)
        1    0.000    0.000    0.421    0.421 frame.py:7625(apply)
        1    0.000    0.000    0.421    0.421 apply.py:141(get_result)
        1    0.000    0.000    0.421    0.421 apply.py:275(apply_standard)
        1    0.000    0.000    0.404    0.404 apply.py:281(apply_series_generator)
      100    0.000    0.000    0.395    0.004 apply.py:109(f)
      100    0.001    0.000    0.395    0.004 group_helpers.py:48(tuples_to_list)
      400    0.003    0.000    0.382    0.001 series.py:964(__seti

In [5]:
def multiple_syninfos(states,repeats):
    for _ in range(repeats):
        syn_info = synergistic_information(JointProbabilityMatrix(3,states),[2],[0,1])

In [7]:
name = 'cProfile_triplet_states4_repeats2'
cProfile.run('multiple_syninfos(4,2)',name)

TRIAL  0
TRIAL  1
TRIAL  2
TRIAL  3
TRIAL  0
TRIAL  1
TRIAL  2
TRIAL  3


In [9]:
p = pstats.Stats('cProfile_triplet_states4_repeats2')
p.strip_dirs().sort_stats('tottime').print_stats(30)

Fri Feb 25 11:01:20 2022    cProfile_triplet_states4_repeats2

         3504580974 function calls (3482233975 primitive calls) in 2028.345 seconds

   Ordered by: internal time
   List reduced from 390 to 30 due to restriction <30>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
290595164  351.409    0.000  444.062    0.000 JointProbabilityMatrix.py:116(__getitem__)
290595164  335.187    0.000  903.471    0.000 JointProbabilityMatrix.py:669(joint_probability)
   597044  271.854    0.000 1053.125    0.002 JointProbabilityMatrix.py:714(marginalize_distribution)
157829/140621  132.992    0.001  556.565    0.004 JointProbabilityMatrix.py:859(append_variables_using_conditional_distributions)
1077532374  127.876    0.000  160.832    0.000 {built-in method builtins.len}
627924371   80.814    0.000   80.814    0.000 {built-in method builtins.hasattr}
199141232   46.360    0.000   46.360    0.000 JointProbabilityMatrix.py:745(<listcomp>)
  7258970   42.186    0.000  125

## save and open cprofilefile

In [6]:
cProfile.run('synergistic_information(a,[2],[0,1])',sort='cumtime')

TRIAL  0
TRIAL  1
TRIAL  2
TRIAL  3
         119735858 function calls (118215964 primitive calls) in 87.881 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   87.881   87.881 {built-in method builtins.exec}
        1    0.000    0.000   87.880   87.880 <string>:1(<module>)
        1    0.000    0.000   87.880   87.880 measures.py:392(synergistic_information)
        4    0.000    0.000   87.697   21.924 measures.py:94(append_synergistic_variables)
        4    0.000    0.000   87.526   21.882 _minimize.py:44(minimize)
        4    0.006    0.001   87.526   21.882 lbfgsb.py:210(_minimize_lbfgsb)
     2793    0.008    0.000   87.388    0.031 _differentiable_functions.py:68(fun_wrapped)
     2793    0.039    0.000   87.380    0.031 save_min_path_class.py:17(simulate)
     2793    0.111    0.000   87.340    0.031 measures.py:154(cost_func_subjects_only)
      147    0.001    0.000   85.662    0.583 

     2804    0.001    0.000    0.001    0.000 {built-in method _thread.get_ident}
     2084    0.001    0.000    0.001    0.000 {method 'rstrip' of 'str' objects}
      147    0.000    0.000    0.001    0.000 _numdiff.py:116(_prepare_bounds)
     3319    0.001    0.000    0.001    0.000 shape_base.py:20(_atleast_1d_dispatcher)
      116    0.000    0.000    0.001    0.000 <__array_function__ internals>:2(copy)
      701    0.001    0.000    0.001    0.000 {method 'find' of 'str' objects}
      147    0.000    0.000    0.001    0.000 fromnumeric.py:1705(ravel)
      294    0.001    0.000    0.001    0.000 {method 'astype' of 'numpy.ndarray' objects}
     2804    0.001    0.000    0.001    0.000 arrayprint.py:507(_array2string_dispatcher)
        4    0.000    0.000    0.001    0.000 measures.py:49(<listcomp>)
      147    0.000    0.000    0.001    0.000 _numdiff.py:127(<listcomp>)
       36    0.000    0.000    0.001    0.000 measures.py:133(<lambda>)
      147    0.000    0.000    0.0

In [18]:
p.strip_dirs().sort_stats('tottime').dump_stats('test')

In [20]:
p = pstats.Stats('test')
p.print_stats()

Sat Feb 19 14:13:05 2022    test

         75289234 function calls (74084065 primitive calls) in 61.043 seconds

   Random listing order was used

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   949082    1.328    0.000    1.973    0.000 <frozen importlib._bootstrap>:1009(_handle_fromlist)
        1    0.000    0.000    0.000    0.000 codecs.py:260(__init__)
        1    0.000    0.000    0.000    0.000 codecs.py:309(__init__)
        7    0.000    0.000    0.000    0.000 codecs.py:319(decode)
   492920    0.137    0.000    0.326    0.000 abc.py:137(__instancecheck__)
     22/4    0.000    0.000    0.000    0.000 abc.py:141(__subclasscheck__)
        4    0.000    0.000    0.000    0.000 _collections_abc.py:72(_check_methods)
        2    0.000    0.000    0.000    0.000 _collections_abc.py:271(__subclasshook__)
       18    0.000    0.000    0.000    0.000 _collections_abc.py:302(__subclasshook__)
        2    0.000    0.000    0.000    0.000 _collections_ab

    36788    0.108    0.000    0.726    0.000 utils.py:5(flatten)
68239/34236    0.082    0.000    0.257    0.000 utils.py:19(<genexpr>)
    27432    0.146    0.000    0.455    0.000 utils.py:9(maximum_depth)
   141777    0.245    0.000    0.285    0.000 utils.py:67(apply_permutation)
    31171    0.361    0.000    3.870    0.000 params_matrix.py:119(params2matrix)
    24484    0.054    0.000    0.121    0.000 params_matrix.py:169(<listcomp>)
52552/24484    0.283    0.000    0.323    0.000 params_matrix.py:417(tree_from_levels)
31171/2229    0.759    0.000   22.074    0.010 params_matrix.py:148(params2matrix_incremental)
603294/273588    0.261    0.000    0.618    0.000 seqs.py:183(flatten)
   318932    0.079    0.000    0.357    0.000 types.py:14(<lambda>)
    24484    0.481    0.000    1.876    0.000 params_matrix.py:370(imbalanced_tree_from_scalars)
        4    0.000    0.000    0.000    0.000 save_min_path_class.py:6(__init__)
     2223    0.031    0.000   60.663    0.027 save_min